services:
  - type: web
    name: vote-service
    env: docker
    buildCommand: "docker build --target dev -t vote-service ./vote"
    dockerfilePath: "./vote/Dockerfile"

  - type: web
    name: redis-service
    env: docker
    dockerfilePath: "./path/to/RedisDockerfile" 
    ipAllowList:
      - "0.0.0.0/0"

  - type: web
    name: result-service
    env: docker
    dockerfilePath: "./result/Dockerfile"

databases:
  - name: postgres-database
    type: postgres
    properties:
      envVars:
        - key: POSTGRES_USER
          value: "postgres"
        - key: POSTGRES_PASSWORD
          value: "postgres"
