
services:
  # Service corresponding to the "vote" service in Docker Compose
  - type: web
    name: vote-service
    env: docker
    buildCommand: docker build --target dev -t vote-service ./vote
    dockerfilePath: ./vote/Dockerfile

  # Redis service from docker-stack.yml with IP allow list
  - type: redis
    name: redis-database
    ipAllowList:
      - 0.0.0.0/0  # Example IP range, adjust as necessary

  # PostgreSQL service from docker-stack.yml
  -  name: postgres-database
    envVars:
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: postgres

  # Result service from docker-compose.images.yml
  - type: web
    name: result-service
    env: docker
    dockerfilePath: ./result/Dockerfile

databases:
  - name: postgres-database
